WINDOW_TITLE = 'Chesserino'
WINDOW_ICON = 'assets\\images\\chess-icon-conv2.png'

MAX_FRAME_PER_SECOND = 60
PLAYER_COUNT = 2

TILE_SIZE_IN_PIXELS = 100
RANK_COUNT = 8
FILE_COUNT = 8
BOARD_SIZE = (RANK_COUNT, FILE_COUNT)

DISPLAY_WIDTH = FILE_COUNT * TILE_SIZE_IN_PIXELS
DISPLAY_HEIGHT = RANK_COUNT * TILE_SIZE_IN_PIXELS
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)

GREEN = (118, 150, 86, 255)
BEIGE = (238, 238, 210, 255)
RED = (160, 0, 0, 255)
